/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alexandre.pageot (https://sketchfab.com/alexandre.pageot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rob-is-on-the-phone-f79ce8f87940478ba197ca8694a1a71d
Title: Rob is on the phone
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect, useRef } from "react"
import { a } from "@react-spring/three";
import robotScene from "../assets/3d/earth_wars_optimus_maximus.glb"
import { LoopOnce } from 'three'; // Import LoopOnce directly from the three library

const ContactRobot = ({currentAnimation,...props})=> {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(robotScene);
  const { actions,mixer} = useAnimations(animations, group,);
  useEffect(()=>{
    console.log(currentAnimation);
  Object.values(actions).forEach(action => action.stop())
  if (actions[currentAnimation] && (currentAnimation==='transform_to_alt_hero') ) {
    actions[currentAnimation].play();
    actions[currentAnimation].setLoop(LoopOnce, 1).clampWhenFinished = true;
  }else if(actions[currentAnimation] && currentAnimation ==='transform_to_main_hero'){
    actions[currentAnimation].play();
    actions[currentAnimation].setLoop(LoopOnce, 1).clampWhenFinished = true;
  }else{
      actions[currentAnimation].play();
  }
  },[actions,currentAnimation])
  return (
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OrangeSauceu (https://sketchfab.com/orangesauceu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-wars-optimus-maximus-3ad4447d16454178b02ffb1f277ee141
Title: Earth Wars Optimus Maximus
*/
    < a.group ref={group} {...props} position={[0, -1 , 0]} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.548}
        >
          <group name="mainfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="trp_optimus_maximus_lod0">
                  <group name="main">
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_8"
                        geometry={nodes.Object_8.geometry}
                        material={materials.OptimusMaximus_0_Chest}
                        skeleton={nodes.Object_8.skeleton}
                      />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.Sunstreaker_0_Body}
                        skeleton={nodes.Object_9.skeleton}
                      />
                      <skinnedMesh
                        name="Object_10"
                        geometry={nodes.Object_10.geometry}
                        material={materials.Ironhide_0_Body}
                        skeleton={nodes.Object_10.skeleton}
                      />
                      <skinnedMesh
                        name="Object_11"
                        geometry={nodes.Object_11.geometry}
                        material={materials.Mirage_0_Body}
                        skeleton={nodes.Object_11.skeleton}
                      />
                      <skinnedMesh
                        name="Object_12"
                        geometry={nodes.Object_12.geometry}
                        material={materials.Optimus_0_Body}
                        skeleton={nodes.Object_12.skeleton}
                      />
                      <skinnedMesh
                        name="Object_13"
                        geometry={nodes.Object_13.geometry}
                        material={materials.OptimusMaximus_0_Body}
                        skeleton={nodes.Object_13.skeleton}
                      />
                      <skinnedMesh
                        name="Object_14"
                        geometry={nodes.Object_14.geometry}
                        material={materials.Prowl_0_Body}
                        skeleton={nodes.Object_14.skeleton}
                      />
                      <group name="OptimuMaximusCombiner_Mesh">
                        <group name="LOD0">
                          <group name="OptimuMaximusCombiner_Body_x0" />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
  }

export default ContactRobot;